#Demonstrate Your Understanding 3

def fibo (x):		#define function that takes parameter x
	sum=0		#initialisation and print
	y=0
	print y
	z=1
	print z
	while (sum<x):		#while condition to check Fibo number does not exceed input
		sum = y + z		#addition
		if(sum>x):		#break out of loop if Fibo number exceeds user input
			break		
		print sum		#print Fibo number
		y=z			#updation of variables 
		z= sum
	
			
		
inp = int(raw_input("Enter the number till which you want the Fibonacci Sequence: "))		#taking user input
print "Here is the Fibonacci Sequence"
fibo(inp)		#function call
		
		
#Explanation: This is a function to print Fibonacci Series numbers according to the user input. The series stops when the last (max) Fibo number is equal to or less than the user inputted number. The code takes in a single input, and passes that to the fibo() function. The fibo() function has the first two numbers of the Fibonacci Series viz 0,1, since they are the staring numbers of the whole sequence. The while loop is initialized with the condition that it should run only if the number generated by the function is less than the number inputted by the user. There is a condition to check if the number generated is more than the input number, if such a thing happens, the loop breaks. This loop is necessary since after the condtion check by the while loop, the new Fibo number is generated and the condition may not hold true as earlier. Beyond the if condtion, the new Fibo number generated is printed. After printing the Fibo number by adding the two previously defined variables, we assign the new number to second variable, and update the value of the first variable. The function does not return any value since all values are printed inside the function. Using the print statement in a function is a not a good way to write a code, but I just wanted to invoke the function only once.
	

